/**
 * Edit copy, paths, and metadata for each of your 7 projects.
 * Image paths are relative to site root.
 *
 * Recommended export: 2560×1440 (16:9) for beauty, process, hero, gallery.
 * Compare pair must share the same resolution and camera framing.
 *
 * Optional compare slider overrides (per project):
 *   compareBefore, compareAfter — image paths (defaults: blockout step or process-02 + beauty)
 *   compareBeforeLabel, compareAfterLabel — e.g. "Clay" / "Final"
 */
const PROJECTS_DATA = [
  {
    slug: "hibiki",
    title: "HIBIKI",
    category: "product",
    year: "2025",
    role: "Lead 3D Artist",
    duration: "3 weeks",
    polycount: "14k tris",
    tools: ["Blender", "Substance Painter", "Octane"],
    summary: "Japanese blended whisky product visualization — amber liquid, cut-glass facets, and warm studio lighting for a premium spirits campaign.",
    problem: "Create a hero bottle and pour shot that feels authentic to Japanese blended whisky — rich amber, label fidelity, and glass caustics — without a physical bottle on set.",
    approach: "Matched label typography and bottle proportions from reference, built layered glass and liquid shaders, and lit with soft key plus rim to emphasize the 24-facet cut and golden whisky tone.",
    outcome: "Final stills delivered for portfolio and pitch deck; client approved lookdev after blockout and greyshade reviews.",
    thumb: "assets/projects/hibiki/beauty.png",
    hero: "assets/projects/hibiki/beauty.png",
    beauty: "assets/projects/hibiki/beauty.png",
    wireframe: "assets/projects/hibiki/wireframe.png",
    gallery: [
      "assets/projects/hibiki/gallery-01.png",
      "assets/projects/hibiki/gallery-02.png",
      "assets/projects/hibiki/gallery-03.png",
    ],
    process: [
      { step: "01 / Concept", caption: "Reference gathering, label layout, and mood for Japanese blended whisky.", image: "assets/projects/hibiki/process-01.png" },
      { step: "02 / Blockout", caption: "Bottle silhouette, label placement, and liquid volume in Blender.", image: "assets/projects/hibiki/process-02.png" },
      { step: "03 / Final", caption: "Beauty render and comp for campaign delivery.", image: "assets/projects/hibiki/process-03.png" },
    ],
    modelGlb: "assets/projects/hibiki/model.glb",
    gridClass: "md:col-span-8",
    aspect: "aspect-video",
    compareBefore: "assets/projects/hibiki/process-02.png",
    compareAfter: "assets/projects/hibiki/beauty.png",
    compareBeforeLabel: "Blockout",
    compareAfterLabel: "Final",
  },
  {
    slug: "liquid-dreams",
    title: "Liquid Dreams",
    category: "visual",
    year: "2024",
    role: "3D Artist",
    duration: "2 weeks",
    polycount: "N/A — still",
    tools: ["Blender", "Photoshop", "After Effects"],
    summary: "Abstract fluid simulation study — metallic ribbons suspended in deep space with soft volumetric glow.",
    problem: "Create a portfolio centerpiece that demonstrates motion, reflection control, and art-direction without narrative constraints.",
    approach: "Combined simulation caches with hand-sculpted correction, then graded in comp for a single cohesive palette.",
    outcome: "Featured in studio reel; used as key visual for digital art print series.",
    thumb: "assets/projects/liquid-dreams/thumb.png",
    hero: "assets/projects/liquid-dreams/hero.png",
    beauty: "assets/projects/liquid-dreams/beauty.png",
    wireframe: "assets/projects/liquid-dreams/wireframe.png",
    gallery: [
      "assets/projects/liquid-dreams/gallery-01.png",
      "assets/projects/liquid-dreams/gallery-02.png",
    ],
    process: [
      { step: "01 / Sim", caption: "Fluid sim base mesh and motion tests.", image: "assets/projects/liquid-dreams/process-01.png" },
      { step: "02 / Sculpt", caption: "Manual cleanup and silhouette refinement.", image: "assets/projects/liquid-dreams/process-02.png" },
      { step: "03 / Light", caption: "HDRI and rim light iteration.", image: "assets/projects/liquid-dreams/process-03.png" },
      { step: "04 / Grade", caption: "Final composite and grain pass.", image: "assets/projects/liquid-dreams/process-04.png" },
    ],
    modelGlb: null,
    gridClass: "md:col-span-4 md:pt-12",
    aspect: "aspect-[3/4]",
  },
  {
    slug: "protocol-09",
    title: "Protocol-09",
    category: "character",
    year: "2023",
    role: "Character Artist",
    duration: "4 weeks",
    polycount: "18k tris",
    tools: ["ZBrush", "Blender", "Substance Painter", "Marmoset"],
    summary: "Cybernetic character bust with emissive circuitry and matte hard-surface panels for a sci-fi IP pitch.",
    problem: "Design a readable hero silhouette at distance while keeping fine panel detail up close for marketing stills.",
    approach: "High-to-low sculpt pipeline, trim sheets for panels, and emissive mask authored in Substance.",
    outcome: "Approved for pitch bible; topology validated for real-time preview in engine.",
    thumb: "assets/projects/protocol-09/thumb.png",
    hero: "assets/projects/protocol-09/hero.png",
    beauty: "assets/projects/protocol-09/beauty.png",
    wireframe: "assets/projects/protocol-09/wireframe.png",
    gallery: [
      "assets/projects/protocol-09/gallery-01.png",
      "assets/projects/protocol-09/gallery-02.png",
      "assets/projects/protocol-09/gallery-03.png",
    ],
    process: [
      { step: "01 / Sculpt", caption: "Primary forms and anatomical landmarks in ZBrush.", image: "assets/projects/protocol-09/process-01.png" },
      { step: "02 / Retopo", caption: "Game-ready topology and UV strategy.", image: "assets/projects/protocol-09/process-02.png" },
      { step: "03 / Texture", caption: "Weathering, emissive masks, and material breakup.", image: "assets/projects/protocol-09/process-03.png" },
      { step: "04 / Present", caption: "Marmoset turntable and beauty lighting.", image: "assets/projects/protocol-09/process-04.png" },
    ],
    modelGlb: "assets/projects/protocol-09/model.glb",
    gridClass: "md:col-span-4",
    aspect: "aspect-square",
  },
  {
    slug: "the-sanctuary",
    title: "The Sanctuary",
    category: "environment",
    year: "2024",
    role: "Environment Artist",
    duration: "5 weeks",
    polycount: "Scene — modular",
    tools: ["Blender", "Unreal Engine 5", "Substance", "Quixel"],
    summary: "Minimalist concrete gallery at night — a luminous portal as focal point with warm interior contrast.",
    problem: "Sell scale and atmosphere in a single still while keeping modular pieces reusable for layout variants.",
    approach: "Modular kitbash, Lumen lighting tests, and fog cards for depth; shot composition guided by leading lines.",
    outcome: "Environment used in cinematic pitch frames; kit approved for greybox expansion.",
    thumb: "assets/projects/the-sanctuary/thumb.png",
    hero: "assets/projects/the-sanctuary/hero.png",
    beauty: "assets/projects/the-sanctuary/beauty.png",
    wireframe: "assets/projects/the-sanctuary/wireframe.png",
    gallery: [
      "assets/projects/the-sanctuary/gallery-01.png",
      "assets/projects/the-sanctuary/gallery-02.png",
    ],
    process: [
      { step: "01 / Greybox", caption: "Blocking scale and camera angles.", image: "assets/projects/the-sanctuary/process-01.png" },
      { step: "02 / Modularity", caption: "Wall and floor modules with trim consistency.", image: "assets/projects/the-sanctuary/process-02.png" },
      { step: "03 / Lighting", caption: "UE5 Lumen + portal emissive balance.", image: "assets/projects/the-sanctuary/process-03.png" },
      { step: "04 / Final", caption: "Marketing still and contact sheet.", image: "assets/projects/the-sanctuary/process-04.png" },
    ],
    modelGlb: null,
    gridClass: "md:col-span-8 md:-mt-24",
    aspect: "aspect-[16/9]",
  },
  {
    slug: "chroma-forge",
    title: "Chroma Forge",
    category: "product",
    year: "2023",
    role: "Product Viz Artist",
    duration: "2 weeks",
    polycount: "8k tris",
    tools: ["Blender", "Substance", "Photoshop"],
    summary: "Weapon / tool concept with heat-treated metal shaders and accent color storytelling.",
    problem: "Communicate craft and function in one hero angle for a tabletop game licensee.",
    approach: "CAD-accurate bevels, tri-planar grunge, and accent lights keyed to brand palette.",
    outcome: "Asset approved for merchandise line; delivered GLB for web viewer.",
    thumb: "assets/projects/chroma-forge/thumb.png",
    hero: "assets/projects/chroma-forge/hero.png",
    beauty: "assets/projects/chroma-forge/beauty.png",
    wireframe: "assets/projects/chroma-forge/wireframe.png",
    gallery: ["assets/projects/chroma-forge/gallery-01.png", "assets/projects/chroma-forge/gallery-02.png"],
    process: [
      { step: "01 / Design", caption: "Silhouette exploration and part separation.", image: "assets/projects/chroma-forge/process-01.png" },
      { step: "02 / Model", caption: "Hard-surface modeling and boolean cleanup.", image: "assets/projects/chroma-forge/process-02.png" },
      { step: "03 / Texture", caption: "Metal wear and color accent passes.", image: "assets/projects/chroma-forge/process-03.png" },
      { step: "04 / Final", caption: "Studio lighting and delivery frames.", image: "assets/projects/chroma-forge/process-04.png" },
    ],
    modelGlb: "assets/projects/chroma-forge/model.glb",
    gridClass: "md:col-span-4",
    aspect: "aspect-square",
  },
  {
    slug: "aurora-drive",
    title: "Aurora Drive",
    category: "product",
    year: "2024",
    role: "Visualization Lead",
    duration: "4 weeks",
    polycount: "Scene",
    tools: ["Blender", "Octane", "Photoshop"],
    summary: "Automotive exterior visualization — wet pavement, neon reflections, and brand-forward camera motion.",
    problem: "Match studio photography quality using only design surfaces and limited HDR references.",
    approach: "Multi-layer comp: CG base, reflection plates, and graded atmosphere; camera matched to brand guidelines.",
    outcome: "Campaign stills delivered for web and print; reel clip used in launch stream.",
    thumb: "assets/projects/aurora-drive/thumb.png",
    hero: "assets/projects/aurora-drive/hero.png",
    beauty: "assets/projects/aurora-drive/beauty.png",
    wireframe: "assets/projects/aurora-drive/wireframe.png",
    gallery: ["assets/projects/aurora-drive/gallery-01.png", "assets/projects/aurora-drive/gallery-02.png", "assets/projects/aurora-drive/gallery-03.png"],
    process: [
      { step: "01 / Ref", caption: "Brand camera and surface analysis.", image: "assets/projects/aurora-drive/process-01.png" },
      { step: "02 / Model", caption: "Surface refinement and panel gaps.", image: "assets/projects/aurora-drive/process-02.png" },
      { step: "03 / Light", caption: "Wet ground and neon rig tests.", image: "assets/projects/aurora-drive/process-03.png" },
      { step: "04 / Comp", caption: "Final grade and lens effects.", image: "assets/projects/aurora-drive/process-04.png" },
    ],
    modelGlb: null,
    gridClass: "md:col-span-8",
    aspect: "aspect-video",
  },
  {
    slug: "void-sentinel",
    title: "Void Sentinel",
    category: "character",
    year: "2023",
    role: "Character Artist",
    duration: "6 weeks",
    polycount: "22k tris",
    tools: ["ZBrush", "Blender", "Substance", "UE5"],
    summary: "Full character concept — armored sentinel with organic corruption veins and cinematic rim lighting.",
    problem: "Balance readable gameplay silhouette with narrative detail for cinematic close-ups.",
    approach: "Split organic and hard-surface workflows; baked combined maps; tested in-engine with parallax and emissive.",
    outcome: "Used as flagship in portfolio reel; mentored junior artist on bake pipeline.",
    thumb: "assets/projects/void-sentinel/thumb.png",
    hero: "assets/projects/void-sentinel/hero.png",
    beauty: "assets/projects/void-sentinel/beauty.png",
    wireframe: "assets/projects/void-sentinel/wireframe.png",
    gallery: ["assets/projects/void-sentinel/gallery-01.png", "assets/projects/void-sentinel/gallery-02.png"],
    process: [
      { step: "01 / Concept", caption: "Thumbnails and armor language.", image: "assets/projects/void-sentinel/process-01.png" },
      { step: "02 / Sculpt", caption: "High-res sculpt and damage pass.", image: "assets/projects/void-sentinel/process-02.png" },
      { step: "03 / Game", caption: "Retopo, bake, and engine test.", image: "assets/projects/void-sentinel/process-03.png" },
      { step: "04 / Cinematic", caption: "Beauty lighting for portfolio.", image: "assets/projects/void-sentinel/process-04.png" },
    ],
    modelGlb: "assets/projects/void-sentinel/model.glb",
    gridClass: "md:col-span-4 md:pt-12",
    aspect: "aspect-[3/4]",
  },
];

const PROJECT_PLACEHOLDER = "assets/projects/_shared/placeholder.svg";

const CATEGORY_LABELS = {
  product: "Product",
  character: "Character",
  environment: "Environment",
  visual: "Visual Arts",
};
